### ISSUE TITLE
Shift-clicking a set opens a new window (Firefox)

### ISSUE THREAD

**Issue by speque** [Sydtrack/ringsdb#10]
In Firefox if one shift-clicks (or shift-alt-clicks) a set in the set selection dropdown a correct set(s) is selected but at the same time a new window pointing to http://ringsdb.com/deck/edit/[DECK_NUMBER_HERE]# is opened.

Tested with Firefox 43.0.1 on OS X. Could not reproduce with Chrome.

**Comment by SnappyTom** [comment]
Rather than a new window, for me shift/alt-shift clicks refresh the current page which resets all the set selections currently made.

Problem exists in Firefox 55 on Win10. Chrome is OK.

**Comment by seastan** [comment]
Can't reproduce in Firefox 61. Is it still an issue for others?

**Comment by seastan** [comment]
Closed due to lack of comment.
