### ISSUE TITLE
Sets drop-down in iOS Safari is too wide (doesn't adjust to mobile screen size)

### ISSUE THREAD

**Issue by mgllghr** [Sydtrack/ringsdb#12]
The Sets drop-down box is too wide when editing a deck in Safari on iOS.  The box is three columns wide so you only get the third column in portrait and the second and third in landscape.  Please consider having it adapt to one long column when it's on a smaller screened device.

Thanks for this awesome site.  It's a huge resource for the entire community!

**Comment by Sydtrack** [comment]
Fixed
