### ISSUE TITLE
Set Selection Dropdown too wide for Mobile

### ISSUE THREAD

**Issue by joezimjs** [Sydtrack/ringsdb#14]
![set-selection-issue](https://cloud.githubusercontent.com/assets/1313898/14253491/4cf4f414-fa51-11e5-8bcb-d692af9a06d0.png)

This is somewhat related to #13 but still a separate issue. When you have the 3 columns, the dropdown is 745px wide, which is too wide for practically any mobile device. Go down to a single column (possibly double column at a mid-size breakpoint) when the device is too small.

**Comment by Sydtrack** [comment]
Thanks a lot for the pull request.

**Comment by joezimjs** [comment]
@Sydtrack No problem. It was a simple fix that I knew I could do without installing and setting everything up.
