### ISSUE TITLE
[Firefox] [Questlog] Quest info does not update

### ISSUE THREAD

**Issue by blueluke** [Sydtrack/ringsdb#23]
And another Firefox-specific bug:
*EDIT: Didn't manage to test this with IE as it won't let me log into the test site. 
Does not affact Chrome/Chromium though.*

When creating a new questlog, selecting a different quest from the selection dropdown does not update the quest information panel - It continues to display the default Passage Through Mirkwood quest stats.

Saving the log and reviewing it will show the correct information, though.
Also the *Randomize* button does work as intended.

**Comment by Sydtrack** [comment]
This is a bug on Firefox itself: https://bugzilla.mozilla.org/show_bug.cgi?id=1024350

I will try to make a alternative fix.
