### ISSUE TITLE
Copy/Paste feature only importing 1 copy of cards

### ISSUE THREAD

**Issue by dylansharek** [Sydtrack/ringsdb#24]
When I copy BBCode from cardgamedb, and use the copy/paste feature to import the deck, only one copy of each card is being put into the deck, even if multiple copies are indicated in the code.

**Comment by Sydtrack** [comment]
Actually I am surprised it even detect some of the cards. I will try to add bbCode support, but for now, the export as text version from CardgameDB works well.

**Comment by seastan** [comment]
No plan to implement bbCode. The text export from CardgameDB works.
