### ISSUE TITLE
Feature request: import zdd deck format

### ISSUE THREAD

**Issue by sparkle999** [Sydtrack/ringsdb#27]
Would be great if you could upload/import zdd file format as produced by Zorbec's LOTR LCG Deckbuilder. That deckbuilder provides various export options however I have not been able to find an option that will work with your upload or import facility.

**Comment by staurasi** [comment]
I would love such feature too. Maybe we can also ask Zorbec for a specific export feature.

**Comment by seastan** [comment]
I don't plan on doing zdd import. I encourage all deckbuiling apps to implement the same export format as cardgamedb so that they can be moved from one deckbuilder to another.
