### ISSUE TITLE
Created Deck Loading Empty

### ISSUE THREAD

**Issue by jmhensey** [Sydtrack/ringsdb#29]
When I open my private decks that have been created with all the cards, it comes up with an empty deck with no added cards despite the preview having the heroes showing on the deck list page.

Decklist Preview:
![heroes](https://cloud.githubusercontent.com/assets/1457738/14991382/f877a504-1115-11e6-9030-15227fddf39b.PNG)

After clicking on deck:
![error](https://cloud.githubusercontent.com/assets/1457738/14991389/fc3c69ea-1115-11e6-8b47-7fd53f50b6fd.PNG)

After Refreshing two times, it finally appears:
![refreshed](https://cloud.githubusercontent.com/assets/1457738/14991428/29cbbe7e-1116-11e6-9891-903f4a059d91.PNG)

**Comment by Sydtrack** [comment]
Which browser are you using?
This was a one time problem or does it happens on every deck?

**Comment by jmhensey** [comment]
Using Firefox. It seems to consistently happen with my personal decks. It will occasionally happen with published decks of others.

**Comment by Sydtrack** [comment]
If you don't mind, there is a dev console on firefox that can be accessed with Ctrl + Shift + J (or F12 and then clicking in Console).

Can you open it before entering a deck and then pasting here the response?

It should be something like this:
![image](https://cloud.githubusercontent.com/assets/1519135/14991924/1ad427c0-113a-11e6-9e4b-8010f8a271fa.png)

**Comment by jmhensey** [comment]
![pt0](https://cloud.githubusercontent.com/assets/1457738/14992162/8bc74dd4-1119-11e6-839b-e41b3aaab9cc.PNG)
![pt1](https://cloud.githubusercontent.com/assets/1457738/14992165/8d8b6678-1119-11e6-9a09-c3692e63e30c.PNG)
![pt2](https://cloud.githubusercontent.com/assets/1457738/14992167/901e4806-1119-11e6-8074-7fd6cb814c15.PNG)
![pt3](https://cloud.githubusercontent.com/assets/1457738/14992170/94d90aac-1119-11e6-82ee-4ef5b14cde4b.PNG)

When I refresh it and it does load, this is added before the first statement:
![workingconsole](https://cloud.githubusercontent.com/assets/1457738/14992176/a390c5a8-1119-11e6-95d1-87d0cf9630bf.PNG)

**Comment by jmhensey** [comment]
It might have to do with the internet to which I'm connected. I'm not using my home wifi. I'll check when I get back to see if I have the same issues.

**Comment by Sydtrack** [comment]
Interesting. Are you behind a proxy?

**Comment by seastan** [comment]
Closed due to lack of comment.
