### ISSUE TITLE
APs Owned not Registering

### ISSUE THREAD

**Issue by jmhensey** [Sydtrack/ringsdb#30]
When I look at decks, cards that I've marked as being owned in my collection are listed with the orange number saying they aren't in my collection. Using Firefox.

APs Selected:
![apsselected](https://cloud.githubusercontent.com/assets/1457738/14991591/f3154656-1116-11e6-8553-885c26072f92.PNG)

Deck saying I don't have the cards:
![incorrectlabel](https://cloud.githubusercontent.com/assets/1457738/14991602/00e172b4-1117-11e6-83a1-a302b3384cd5.PNG)

**Comment by Sydtrack** [comment]
I am not able to reproduce this either. This may be related to the latest cache policies. Will investigate further. I have set the same Adventure packs and loaded the same decklist and I have the following image:

![image](https://cloud.githubusercontent.com/assets/1519135/14991789/8640daae-1139-11e6-8358-cda6eb5718ae.png)

**Comment by seastan** [comment]
Closed due to lack of comment.
