### ISSUE TITLE
Search by Uniqueness / Errata

### ISSUE THREAD

**Issue by mplain** [Sydtrack/ringsdb#33]
Searching by Uniqueness doesn't do anything.

Searching by Errata instead searches by uniqueness.

I'm referring to the main Search page.

P.S. Cool site, thanks for it! Is it meant to serve as a deckbuilder only, or are you planning to add encounter cards too, for the completeness of the database?

**Comment by Sydtrack** [comment]
Fixed thanks to @olivierkes
