### ISSUE TITLE
See a list of the most recent decks on the front page too

### ISSUE THREAD

**Issue by nthorn** [Sydtrack/ringsdb#34]
It's really hard for new decks to get enough likes to get on the front page since most people only look at the "top 4" decks on the front page. It usually just ends up being a timing thing, where decks get on the front page simply by being the newest deck at the time when the last deck of that color "ages out".

This could be alleviated somewhat if the front page also featured a less prominent list of say, the 10 newest decks (regardless of popularity). This way new decks could get a little publicity before they are banished to the dark corners of the Decklists page.

**Comment by seastan** [comment]
Closed by #57
