### ISSUE TITLE
Add a feed rss/atom for reviews

### ISSUE THREAD

**Issue by fipm** [Sydtrack/ringsdb#36]
I am trying to set up a profile for ringdb using Hermit - an android app that integrates websites adding notifications and quick edit options. A rss feed for reviews would allow the app to notify me when a new review is added. Maybe the functionality would be useful also to those who aggregate the most popular blogs about the game (I do that too).

**Comment by seastan** [comment]
I have set up an RSS feed for card reviews here: http://createfeed.fivefilters.org/extract.php?url=ringsdb.com%2Freviews&in_id_or_class=card-name&url_contains=
