### ISSUE TITLE
[Wish] Add autosave to deck builder

### ISSUE THREAD

**Issue by olivierkes** [Sydtrack/ringsdb#41]
When using the deck builder on my mobile phone, it happened many times that as a leave the page to do something else, when i come back the page has to be reloaded and all the edits are lost.

An autosave in the backgroud would smooth the experience.

**Comment by Sydtrack** [comment]
There is an autosave feature. It will store changes in the History Tab.
After a reload, if it seemed you lost some changes, check the History Tab
to restore them.

--
Alberto Wagner

**Comment by olivierkes** [comment]
Woops sorry. RingsDB is great :)
