### ISSUE TITLE
Https certificate expired?

### ISSUE THREAD

**Issue by Amerithrash** [Sydtrack/ringsdb#43]
Hi, I'm trying to log into my account, and Chrome is giving me the following error:

# Your connection is not private

Attackers might be trying to steal your information from ringsdb.com (for example, passwords, messages, or credit cards). NET::ERR_CERT_DATE_INVALID

**Comment by Sydtrack** [comment]
Fixing it right now.

**Comment by Sydtrack** [comment]
Fixed.
