### ISSUE TITLE
[Request/Wish] "exclude" for deck searches

### ISSUE THREAD

**Issue by SaraUii** [Sydtrack/ringsdb#46]
When searching for decks it would be cool to have any kind of exclude filter (not only an include one). So, that you could e.g. search for decks with hero Gandalf (as it is right now) but additionally specify to have no heroes with a Hobbit trade. Or you wish to find a multiplayer friendly deck and you want to exclude the Steward of Gondor.

**Comment by Sydtrack** [comment]
This could complete #47, if there is a way to also exclude some spheres.

**Comment by seastan** [comment]
Implemented card exclusion. It should be available in the next update.
