### ISSUE TITLE
Not receiving registration email

### ISSUE THREAD

**Issue by plerf** [Sydtrack/ringsdb#48]
Not sure if this is the right place for this issue, but couldn't find anywhere else. I created an account on Tuesday the 26th, but have yet to receive a registration email. If I attempt to log in I get a message saying the account is disable, and I have clicked the "never received a registration email?" link several times in the last few days but still haven't received the e-mail. I also tried registering again in case I had entered my e-mail address wrong, but it tells me the e-mail is already used so that's not the issue. I tried registering with a different e-mail today and also haven't received an e-mail for that one.

**Comment by replicaJunction** [comment]
I'm also experiencing this issue.

**Comment by stevenf544** [comment]
I'm having the same problem, I've tried with multiple email accounts and hosts, appears to be a site issue.

**Comment by Sydtrack** [comment]
Checking this problem...

**Comment by Sydtrack** [comment]
Digital Ocean started blocking smtp ports. I'm contacting them to fix this issue.

**Comment by victorfmin66** [comment]
Im having the same issue too...
