### ISSUE TITLE
Limited Edition Starter

### ISSUE THREAD

**Issue by thozam** [Sydtrack/ringsdb#63]
Checking this pack does not seem to add cards to collection other than the 2 new heroes.

**Comment by seastan** [comment]
This is currently intended. The remaining cards in the starter already exist on ringsdb, and we wanted to avoid duplicates.

**Comment by thozam** [comment]
Ok, I understand that.
But how can I see the cards in my collection?
I'm a beginner with a 1 Starter and 1 Core set, plus some other early packs.
When I'm trying to build a deck I only see 1 copy of Unexpected Courage, as an example.
I apologize if I am missing something obvious here.

**Comment by seastan** [comment]
That does seem like a compelling reason to add the remaining cards. I will get started on that.

In the meantime, if you go into the collection and select 3 core sets, you should have access to 3 Unexpected Courages.

**Comment by thozam** [comment]
Excellent news!

**Comment by seastan** [comment]
@thozam I added the Starter set to ringsdb. Can you confirm that it now functions in the way you desire?

**Comment by thozam** [comment]
Thank you very much! I just checked quickly and it looks very good.
Hopefully there are more new players that can benefit from this.
