### ISSUE TITLE
Tooltip popup out of view on mobile friendly version

### ISSUE THREAD

**Issue by onesacker15** [Sydtrack/ringsdb#7]
One thing I found though when looking at a deck, when I click on an ally/attachment/event, the tooltip window will popup off screen of my phone partially out of view. I am not sure if it's just me but I am using an iPhone 6. it seems that it depends on the size of the tooltip window. If it's too big it will pop up over on the left of the name out of view, but if small enough it will still pop in view.

**Comment by Sydtrack** [comment]
Fixed by removing the first tooltip with mobile users.
